// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PARKit.Backend.Data;

#nullable disable

namespace PARKit.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601154257_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PARKit.Backend.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ElectricVehicle")
                        .HasColumnType("bit");

                    b.Property<bool>("LargeVehicle")
                        .HasColumnType("bit");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Car", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ElectricVehicle = true,
                            LargeVehicle = false,
                            Matricule = "1234ABC",
                            Name = "Toyota Prius",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ElectricVehicle = false,
                            LargeVehicle = false,
                            Matricule = "5489zyc",
                            Name = "Ford F-150",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("PARKit.Backend.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CIF = "B99123456",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@zaragozaparking.es",
                            IsActive = true,
                            NameCompany = "Zaragoza Parking SL",
                            PasswordHash = "$2a$11$3nkmEw7ZTpaGcNUoivdB4eJnaesAHoL06b9J6Ke0KiX5/MRmumz/K",
                            Phone = "976123456",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            CIF = "A58974555",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "gran@zaragozaparking.es",
                            IsActive = true,
                            NameCompany = "Gran Parking SL",
                            PasswordHash = "$2a$11$wPui/TbgDqMVfRXvOV7ehOLEC6MYjdli4KGSVJ96qOca4S4qQPbPm",
                            Phone = "976885621",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("PARKit.Backend.Models.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("ParkingId")
                        .HasColumnType("int");

                    b.Property<string>("SpotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParkingId");

                    b.ToTable("ParkingSpot", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParkingId = 1,
                            SpotNumber = "A-1",
                            Status = 0,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 2,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParkingId = 1,
                            SpotNumber = "A-2",
                            Status = 1,
                            Type = "Electric"
                        },
                        new
                        {
                            Id = 3,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParkingId = 1,
                            SpotNumber = "A-3",
                            Status = 0,
                            Type = "Electric"
                        },
                        new
                        {
                            Id = 4,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParkingId = 1,
                            SpotNumber = "A-4",
                            Status = 1,
                            Type = "Electric"
                        },
                        new
                        {
                            Id = 5,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParkingId = 2,
                            SpotNumber = "B-1",
                            Status = 1,
                            Type = "Large"
                        },
                        new
                        {
                            Id = 6,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParkingId = 2,
                            SpotNumber = "B-2",
                            Status = 0,
                            Type = "Large"
                        },
                        new
                        {
                            Id = 7,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParkingId = 2,
                            SpotNumber = "B-3",
                            Status = 1,
                            Type = "Large"
                        });
                });

            modelBuilder.Entity("PARKit.Backend.Models.Parkings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeometryData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Parkings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Calle Mayor, 1, Zaragoza",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Parking en el centro de Zaragoza",
                            IsActive = true,
                            Latitude = 41.656100000000002,
                            Longitude = -0.87729999999999997,
                            Name = "Parking Central",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Avenida del Fútbol, 10, Zaragoza",
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Parking cerca del estadio de fútbol",
                            IsActive = true,
                            Latitude = 41.674199999999999,
                            Longitude = -0.89049999999999996,
                            Name = "Parking Norte",
                            Type = 1
                        });
                });

            modelBuilder.Entity("PARKit.Backend.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5.00m,
                            ClientSecret = "pi_test_12345",
                            Currency = "EUR",
                            ExternalTransactionId = "ch_54321_stripe",
                            PaymentDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservationId = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("PARKit.Backend.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CadType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastFourDigits")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethod", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CadType = "Visa",
                            ExpiryDate = "05/28",
                            HolderName = "JUAN PEREZ",
                            LastFourDigits = "4242",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CadType = "Mastercard",
                            ExpiryDate = "12/27",
                            HolderName = "MARIA GARCIA",
                            LastFourDigits = "1234",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("PARKit.Backend.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParkingSpotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ParkingSpotId");

                    b.ToTable("Reservation", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            EndTime = new DateTime(2026, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ParkingSpotId = 1,
                            StartTime = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 4,
                            TotalAmount = 5.00m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            EndTime = new DateTime(2026, 6, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            ParkingSpotId = 3,
                            StartTime = new DateTime(2026, 6, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3,
                            TotalAmount = 5.00m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("PARKit.Backend.Models.Tarif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ElectricVehicleSurcharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("bit");

                    b.Property<decimal>("LargeVehicleSurcharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NameTarif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParkingId")
                        .HasColumnType("int");

                    b.Property<int?>("ParkingsId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan?>("StarTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParkingsId");

                    b.ToTable("Tarif", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ElectricVehicleSurcharge = 0m,
                            EndTime = new TimeSpan(0, 22, 59, 59, 0),
                            IsHoliday = false,
                            LargeVehicleSurcharge = 0m,
                            NameTarif = "Tarifa General Día",
                            ParkingId = 1,
                            PricePerHour = 2.50m,
                            StarTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            ElectricVehicleSurcharge = 0m,
                            EndTime = new TimeSpan(0, 7, 59, 59, 0),
                            IsHoliday = false,
                            LargeVehicleSurcharge = 0m,
                            NameTarif = "Tarifa Nocturna",
                            ParkingId = 1,
                            PricePerHour = 1.50m,
                            StarTime = new TimeSpan(0, 23, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            ElectricVehicleSurcharge = 0m,
                            IsHoliday = false,
                            LargeVehicleSurcharge = 0m,
                            NameTarif = "Tarifa Única",
                            ParkingId = 2,
                            PricePerHour = 3.00m
                        },
                        new
                        {
                            Id = 4,
                            ElectricVehicleSurcharge = 0m,
                            IsHoliday = false,
                            LargeVehicleSurcharge = 0m,
                            NameTarif = "Suplemento Coche Grande",
                            ParkingId = 1,
                            PricePerHour = 1.20m
                        },
                        new
                        {
                            Id = 5,
                            ElectricVehicleSurcharge = 0m,
                            IsHoliday = false,
                            LargeVehicleSurcharge = 0m,
                            NameTarif = "Tarifa Eléctrico",
                            ParkingId = 1,
                            PricePerHour = 1.50m
                        });
                });

            modelBuilder.Entity("PARKit.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAT")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAT = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "juan@test.com",
                            IsActive = true,
                            Name = "Juan",
                            PasswordHash = "$2a$11$Zl7IcnyMerg47s9wkOQoeOvNWBvIKPAHC7MdKSXJL5K9Olbh.FV9e",
                            Phone = "600123456",
                            Role = "User"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAT = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria@test.com",
                            IsActive = true,
                            Name = "María",
                            PasswordHash = "$2a$11$bItMyCdlqv2PzPiSyn9qTu5V7kLF0XkuMoHc5EPEa7nGyoVs.PFh6",
                            Phone = "689745213",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("PARKit.Backend.Models.ParkingSpot", b =>
                {
                    b.HasOne("PARKit.Backend.Models.Parkings", "Parking")
                        .WithMany("ParkingSpots")
                        .HasForeignKey("ParkingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parking");
                });

            modelBuilder.Entity("PARKit.Backend.Models.Reservation", b =>
                {
                    b.HasOne("PARKit.Backend.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PARKit.Backend.Models.ParkingSpot", "ParkingSpot")
                        .WithMany()
                        .HasForeignKey("ParkingSpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("ParkingSpot");
                });

            modelBuilder.Entity("PARKit.Backend.Models.Tarif", b =>
                {
                    b.HasOne("PARKit.Backend.Models.Parkings", null)
                        .WithMany("Tarifs")
                        .HasForeignKey("ParkingsId");
                });

            modelBuilder.Entity("PARKit.Backend.Models.Parkings", b =>
                {
                    b.Navigation("ParkingSpots");

                    b.Navigation("Tarifs");
                });
#pragma warning restore 612, 618
        }
    }
}
